# vim:ts=2:sw=2:sts=2
# SEE:
#   https://github.com/skycaptain/gazetrack/blob/master/gui/pyqtgraph/.travis.yml
#   https://github.com/pyqt/python-qt5/wiki/Compiling-PyQt5-on-Ubuntu-12.04
#   http://stackoverflow.com/questions/20952797/pip-installing-in-global-site-packages-instead-of-virtualenv
#   http://code.openhub.net/file?fid=0PrA9WLQQDK3eJTLHrBLVqIggdM&cid=2f70lFT6IOE&s=

sudo: false
language: python
python:
  # - "2.7"
  # - "3.3"
  - "3.4"
  # - "nightly"

# virtualenv:
#   system_site_packages: true

# before_install:
  # Qt5
  # - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  # - sudo apt-get update -qq
  # - sudo apt-get install -qq python3-pyqt5
    # if sys.version_info[0] == 3: sudo apt-get install -qq python3-pyqt5
    # else: sudo apt-get install -qq python-qt5
  # - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev
  # - sudo apt-get install -y qt5-default qttools5-dev-tools

# Cached Downloads
  # - sudo mkdir -p /downloads
  # - sudo chmod a+rw /downloads
  # - if [ ! -f /downloads/sip.tar.gz ]; then curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz; fi
  # - if [ ! -f /downloads/pyqt5.tar.gz ]; then curl -L -o /downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4/PyQt-gpl-5.4.tar.gz; fi
  # - echo '6d01ea966a53e4c7ae5c5e48c40e49e5  /downloads/sip.tar.gz' | md5sum -c -
  # - echo '7f2eb79eaf3d7e5e7df5a4e9c8c9340e  /downloads/pyqt5.tar.gz' | md5sum -c -
  #
  # # Builds
  # - sudo mkdir -p /builds
  # - sudo chmod a+rw /builds


# install:
  # - sudo apt-get install -qq python3-pyqt5 --fix-missing
  # # Builds
  # - pushd /builds
  #
  # # SIP
  # - tar xzf /downloads/sip.tar.gz --keep-newer-files
  # - pushd sip-4.16.5
  # - python configure.py
  # - make
  # - sudo make install
  # - popd
  #
  # # PyQt5
  # - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
  # - pushd PyQt-gpl-5.4
  # - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets -e QtNetwork
  # - make
  # - sudo make install
  # - popd
  # # Builds Complete
  # - popd

  # Dependencies
# - pip install .  # If you have 'setup.py' to install as package
install:
  - python --version
  - pip --version
  - pip install -Ur requirements.txt
  - pip search PyQt5; cat $HOME/.pip/pip.log

  # debug:
  - apt-cache search python pip
  - apt-cache search python qt5

before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3
  - which python
  - which py.test
  - python --version

script:
  PYTHONPATH=. PYTEST_QT_API=pyqt5 py.test -- $PWD
  # - make test

# after_script:
#   - if [ $COV ]; then
#     sudo pip install --quiet coveralls;
#     coveralls;
#     fi

# cache:
#   # directories:
#   #   - /downloads
#   apt: true

notifications:
  email: false
  webhooks:
    # urls:
    #   - https://webhooks.gitter.im/e/0ed6fa8828890c4a49ea
    on_success: change
    on_failure: always
    on_start: false

# deploy:
#   provider: pypi
#   user: ...
#   distributions: "sdist"
#   password:
#     secure: ...=
#   on:
#     tags: true
#     all_branches: true
