# vim:ts=2:sw=2:sts=2

sudo: false
language: python
python:  # Need python >= 3.3
  # - "3.3"
  - "3.4"
  # - "nightly"

# virtualenv:
#   system_site_packages: true

addons:
  apt:
    packages: [gcc, g++, python3-dev, qtbase5-dev, qt5-qmake]

before_install:
  - bash ./scripts/site/travis-before

# before_install:
  # Qt5
  # - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  # - sudo apt-get update -qq
  # - sudo apt-get install -qq python3-pyqt5
    # if sys.version_info[0] == 3: sudo apt-get install -qq python3-pyqt5
    # else: sudo apt-get install -qq python-qt5
  # ALT - sudo apt-get install -qq python3-pyqt5 --fix-missing
  # - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev
  # - sudo apt-get install -y qt5-default qttools5-dev-tools

  # Dependencies
# - pip install .  # If you have 'setup.py' to install as package
install:
  # - pip install -U pip
  # - pip --version
  - pip install -U PyYAML
  - pip install -U pytest pytest-cov pylint pep8
  # python-qt5 pytest-qt
  - bash ./scripts/site/travis-install

cache:
  directories:
    - $HOME/dld
  apt: true

before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3
  - which python
  - which py.test

script:
  # NOTE: now I removed all qt-dependent tests
  # - FLS=$(find "$PWD/tests/" -type f -name '*_test.py' \! -name 'ringsegment*')
  - PYTHONPATH=. PYTEST_QT_API=pyqt5 py.test --cov=piony --cov-report term-missing
  # - make test

# after_script:
#   - if [ $COV ]; then
#     sudo pip install --quiet coveralls;
#     coveralls;
#     fi

after_success:
  - pip install -U python-coveralls
  - coveralls

notifications:
  email: false
  webhooks:
    # urls:
    #   - https://webhooks.gitter.im/e/0ed6fa8828890c4a49ea
    on_success: change
    on_failure: always
    on_start: false

# deploy:
#   provider: pypi
#   user: ...
#   distributions: "sdist"
#   password:
#     secure: ...=
#   on:
#     tags: true
#     all_branches: true
