language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  - "3.4"
  # - "nightly"

# before_install:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sudo apt-get update -qq
#   - sudo apt-get install -y python3-pyqt5

sudo: false

install:
# - pip install .  # If you have 'setup.py' to install as package
  - pip3 install PyYAML pytest pytest-qt pylint pep8
  - pip3 install python-qt5

script:
  - make test
