#!/bin/bash -e
cd "$(readlink -m ${0%/*})"

./screenshots ./tests

montage /tmp/piony/*.png \
    -tile 3x -frame 2 -shadow -geometry '+5+5' \
    -font DejaVu-Sans-Mono -background none \
    /tmp/collage.png
