#!/bin/bash -e
# vim:ts=2:sw=2:sts=2

DIR="$HOME/dld"

mkdir -p "$DIR"
chmod a+rw "$DIR"

if [[ ! -f "$DIR"/sip.tar.gz ]]; then
  curl -L -o "$DIR"/sip.tar.gz \
    http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz
fi
if [[ ! -f /downloads/PyQt.tar.gz ]]; then
  curl -L -o "$DIR"/PyQt.tar.gz \
    http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4/PyQt-gpl-5.4.tar.gz
fi

echo "6d01ea966a53e4c7ae5c5e48c40e49e5  $DIR/sip.tar.gz"  | md5sum -c -
echo "7f2eb79eaf3d7e5e7df5a4e9c8c9340e  $DIR/PyQt.tar.gz" | md5sum -c -
