#!/usr/bin/env bash
# Use it regularly to update pip packages!

# python-pip pyqt5-dev
sudo apt-get install python3-dev python3-pip python3-pyqt5 python3-yaml
sudo pip3 install -U pytest pep8
sudo pip3 install -U pylint
sudo pip3 install -U ipython ipdb pudb

# python3-sip
#   SIP is a tool for quickly writing Python modules that interface with C++ and C libraries
#       http://riverbankcomputing.co.uk/software/sip/intro

