#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
source ./funcs

if distro arch; then
    pkg_inst python python-pyqt5 python-pip

elif distro ubuntu; then
    pkg_inst python3 python3-pyqt5 python3-pip
fi

# python3-yaml
sudo pip3 install -U PyYAML inject
