#!/usr/bin/env bash

### PROFILING ###
sudo apt-get install kcachegrind graphviz #python-matplotlib
# kcachegrind        # to see profile results in GUI
# graphviz           # for gprof2dot
# python3-matplotlib # for memory_profiler
sudo pip3 install -U pyprof2calltree gprof2dot
sudo pip3 install -U line_profiler pprofile
sudo pip3 install -U psutil memory_profiler matplotlib
