#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
source ./funcs

pkg_inst python-pytest

if distro arch; then
    pkg_inst python-pylint #pep8
    pkg_inst ipython python-ipdb
    pkg_inst python-pytest-cov

elif distro ubuntu; then
    sudo pip3 install -U pylint pep8
    sudo pip3 install -U ipython ipdb
    sudo pip3 install -U pytest-cov pytest-qt
fi
### DEVELOP ###
# sudo pip3 install -U readline pyreadline pudb
# sudo pip3 install -U git+git://github.com/mverteuil/pytest-ipdb.git
# readline # for adequate navigation in IPython cmdline
# ipdb     # pretty debugger for IPython

# python3-sip
#   SIP is a tool for quickly writing Python modules that interface with C++ and C libraries
#       http://riverbankcomputing.co.uk/software/sip/intro
