#!/usr/bin/env bash
# Extract changelog from completed tasks

SDIR="$(readlink -m ${0%/*})"
PROJ="${SDIR%/*/*}"
cd "$PROJ"

FL=${1:-./TODO.otl}
VERFL=./piony/__init__.py

{
    git rev-list --all  -- "$VERFL" | while read line; do
        dt=$(git show -s --format=%ci $line | awk '{printf $1}')
        ver=$(git cat-file -p $line:"$VERFL" \
            | sed -rn '/.*__version__\s*=\s*"(\S+)"/s//\1/p')
        echo "$dt --- version $ver ---"
    done

    find . -name '*.otl' -exec cat {} \; | sed -rn '/(\s*)(.*)(\[[X$~]\]\s.*)/s//\2\1\3/p'

} | sort -rn | sed -r '/.*(--- version.*)/s//\n\1/' | less
